### Site info:
title: Freshman
tagline: IT, Android, iOS, PHP
author: Kurtis Hu
email: whdxs@126.com
description: "Kurtis's private blog" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "IT, Android, iOS, PHP"
baseurl: "/en" # the subpath of your site, e.g. /blog
url: "http://kurtis.hu.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: KurtisHu
github_username:  KurtisHu
disqus_shortname: kurtishu
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Kurtis. I made the Freshman21 theme. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Kurtis
      href: http://yulijia.net/freshman21
      title: Another Jekyll blog theme
    - name: author's website
      href: http://yulijia.net/
      title: Kurtis's website


### Build settings
markdown: kramdown
highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
